### PR TITLE
Adds 'delete this paste' link, confirmation form, functionality.

### PR DESCRIPTION
**Pull request by coddingtonbear**

### CODE REVIEW

**Comment by coddingtonbear** [comment]
Whoops; sorry @thekad -- was only intending to PR this against UA's fork.

**Comment by thekad** [comment]
@coddingtonbear this looks like something other people would benefit from, if you wanna reopen I can take a deeper look?

**Comment by coddingtonbear** [comment]
Would, but I really didn't polish the feature enough that I think it's something I'd feel comfortable endorsing as a feature; it is really ugly the way that I made paste deletion work with password-protected pastes.  I just hacked it together so we could have a delete button in the event of somebody accidentally posting a secret to a paste somewhere.

**Comment by thekad** [comment]
Ah I see. Pro tip: you'd need to recursively search for all children pastes (if any) to also delete them in that case.

**Pull request closed without merging**
